### ISSUE TITLE
Add build dependencies to README

### ISSUE THREAD

**Issue by beriberikix** [Ribbit-Network/ribbit-network-frog-software#29]
I can infer the dependencies from the Makefile but having cross-platform instructions would be helpful.

**Comment by keenanjohnson** [comment]
Good idea @beriberikix! 

In addition to just documenting the dependencies, do you think it would also be helpful to provide a VSCode dev container that can be easily opened locally and already has all the dependencies installed?

**Comment by beriberikix** [comment]
That would be a nice addition! I've never used them personally but they seem cool.

**Comment by keenanjohnson** [comment]
Done!
